---
title: 'Séance 4.1: Mesures de tendances centrales'
author: "Visseho Adjiwanou, PhD."
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

## Paramètres de position

Vous venez de faire une enquête auprès de 30 personnes dont 17 femmes et 13 hommes. Les revenus (en millier) des 17 femmes sont les suivantes: 2, 3, 4, 1, 3, 7, 4, 1, 3, 6, 3, 5, 5, 3, 8, 3, 9.
Les revenus des hommes sont: 5, 6, 3, 4, 4, 9, 7, 5, 5, 3, 3, -, 8

- Calculer la moyenne, le mode, la médiane, le 1e quartile et le 3e quartile pour les femmes et pour les hommes

**Femmes**

- Mode : 3 (la plus grande fréquence)
- Moyenne : (2 + 3 + 4 + 1 + 3 + 7 + 4 + 1 + 3 + 6 + 3 + 5 + 5 + 3 + 8 + 3 + 9)/17= 4.1
- Médiane: 1, 1, 2, 3, 3, 3, 3, 3, **3**, 4, 4, 5, 5, 6, 7, 8, 9
(17+1)/2 = 9, valeur située à la 9e position. Md = 3

- 1 quartile: 1, 1, 2, **3, 3**, 3, 3, 3
8/2 = 4; Entre la 4e et la 5e valeur: (3+3)/2 = 3

- 3e quartile: 4, 4, 5, **5, 6**, 7, 8, 9
    Q3 = (5+6)/2 = 5,5 

En conclusion

1, 1, 2, 3,*Q1* 3, 3, 3, 3, **3 (Md)**, 4, 4, 5, 5,*Q3*, 6, 7, 8, 9

Faites la même chose pour les hommes

## Où y'a-t-il plus d'inégalité de revenu? chez les hommes où chez les femmes.

La moyenne seule ne permet pas de répondre à cette question. le revenu moyen chez les hommes est de: 5167 dollars. Alors que chez les femmes, le revenu moyen vaut 4118 dollars. Pour connaître la réponse, il faut calculer les paramètres de variation.

## Paramètres de variation

- étendue: 9-1 = 8
- Écart inter-quartile = 5,5 - 3 = 2,5
- Variance

   (X - Moy)     (X - Moy)^2
1  1-4.1 = -3.1  (-3.1)^2 = 9.61  
1  1-4.1 = -3.1  (-3.1)^2 = 9.61
2  2-4.1 = -2.1  (-2.1)^2 = 4.41
3  3-4.1 = -1.1  (-1.1)^2 = 1.21
3  3-4.1 = -1.1  (-1.1)^2 = 1.21
3  3-4.1 = -1.1  (-1.1)^2 = 1.21
3  3-4.1 = -1.1  (-1.1)^2 = 1.21
3  3-4.1 = -1.1  (-1.1)^2 = 1.21
3  3-4.1 = -1.1  (-1.1)^2 = 1.21
4  4-4.1 = -0.1  (-0.1)^2 = 0.01
4  4-4.1 = -0.1  (-0.1)^2 = 0.01 
5  5-4.1 =  0.9  ( 0.9)^2 = 0.81
5  5-4.1 =  0.9  ( 0.9)^2 = 0.81
6  6-4.1 =  1.9  ( 1.9)^2 = 3.61
7  7-4.1 =  2.9  ( 2.9)^2 = 8.41
8  8-4.1 =  3.9  ( 3.9)^2 = 15.21
9  9-4.1 =  4.9  ( 4.9)^2 = 24.01


Somme (X-Moy) = -3.1 -3.1 -2.1 -1.1 -1.1 -1.1 -1.1 -1.1 -1.1 -0.1 -0.1 + 0.9 + 0.9 + 1.9 + 2.9 + 3.9 + 4.9 = 

Variance = Somme (X-Moy)^2/(17-1) = (9.61 + 9.61 + 4.41 + 1.21 + 1.21 + 1.21 + 1.21 + 1.21 + 1.21 + 0.01 + 0.01 + 0.81 + 0.81 + 3.61 + 8.41 + 15.21 + 24.01)/16 + 5.235625

Variance = 5.235625 * 1000^2 = 5 235 625

- On va lui préférer la racine carrée qui donne l'écart-type

- Écart-type : racine carré(variance) = 2288 dollars. Vous voyez, cela se mesure dans la même unité que la variable.

