---
title: "Labo 1: Statistiques et variables"
author: "Visseho Adjiwanou, PhD."
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document: default
  html_document: default
---

## Exercice 1: Du concept à la mesure

Marx a soutenu que le capitalisme est un mode de production économique basé sur le conflit entre deux classes de personnes: le capital (alias la bourgeoisie) et le travail (alias le prolétariat). L'appartenance à une classe est déterminée par sa relation avec les moyens de production. Le capital possède les moyens de production et le travail non. Au travail, les membres de la classe ouvrière vendent leur capacité de faire du travail (leur force de travail) au capital en échange d'un taux de salaire. Marx a affirmé que cela a pour effet d'aliéner les gens de leur travail parce que les individus ne contrôlent plus leur travail, ni le produit de leur travail.

Logiquement, cela a du sens; cependant, pouvons-nous mesurer l'aliénation d'une manière ou d'une autre pour offrir des preuves empiriques de son existence? L'aliénation de Marx existe au niveau conceptuel. Pouvez-vous penser à des moyens d'opérationnaliser l'aliénation?

Aliénation: condition dans laquelle les gens souffrent d'une «déconnexion» entre eux-mêmes et de leur travail et d'une déconnexion les uns des autres.

### Réponse

Vous ne vous souciez peut-être pas beaucoup de ce que vous faites pour le travail tant que vous gagnez suffisamment d'argent. D'un autre côté, vous préférerez peut-être sacrifier un revenu pour un travail qui vous donne beaucoup de satisfaction, c'est-à-dire un travail moins aliénant. À partir de cela, nous pourrions supposer que les personnes qui aiment le type de travail qu'elles effectuent sont moins éloignées de leur travail que les personnes qui n'aiment pas le type de travail qu'elles font.

Bien que nous ne puissions pas saisir l'aliénation et la mettre sur une échelle pour voir dans quelle mesure une personne en fait l'expérience, nous pouvons demander aux gens s'ils sont susceptibles de rester à un emploi pour le revenu ou de sacrifier un revenu pour un emploi qu'ils aiment. Ceux qui indiquent qu'ils seraient disposés à prendre moins de salaire mais qui ont un emploi qu'ils aiment seraient ceux qui connaissent un niveau d'aliénation plus faible. De cette façon, nous avons pris le concept d'aliénation et l'avons opérationnalisé comme variable.

Seriez-vous prêt à accepter une réduction de salaire pour avoir un emploi qui vous plaît plus que votre emploi actuel?
- Oui
- Non

Un problème qui se pose avec cette variable est qu'elle comporte un biais de classe. En d'autres termes, les personnes qui ne gagnent pas assez d'argent pour joindre les deux bouts sont beaucoup plus susceptibles de répondre «non». Par conséquent, nous n'avons pu comparer que les réponses des répondants de classe relativement similaire. Nous pourrions affirmer que ceux qui répondent «oui» connaissent des niveaux d'aliénation plus importants de leur travail que ceux qui répondent «non».

Plusieurs facteurs doivent être pris en compte lors de l'opérationnalisation d'une variable. Deux d'entre eux sont que la variable doit être (1) collectivement exhaustive et (2) mutuellement exclusive.




## Exercice 2: Variable dépendante, variable indépendante

Parmi les exemples suivants, identifier les variables et dire si elles constituent dans le contexte une variable dépendante ou indépendante. Définissez aussi le type de variable en question.

1. Une démographe analyse l'évolution du taux de fécondité des femmes depuis 1960 selon l'origine ethnique et le degré de scolarité.

  - **VD : taux de fécondité (ratio)**
  - **VI : origine ethnique (nominale), degré de scolarité (ordinale, ratio)**

2. Dans une expérience sur le temps de réaction visuelle, on mesure le temps nécessaire pour percevoir des mots à connotation sexuelle par rapport à  des mots non sexuels. Pour cette expérience, les chercheurs prennent bien soin de s'assurer que la vision des sujets leur permet de voir adéquatement les diapositives.

  - **VD: Temps de réaction visuel (ratio)**
  - **VI: Connotation des mots (nominale)**

3. Un criminologue recherche des données sur la nature des infractions au Code criminel selon le sexe des accusés.

4. Lors d'une série d'expérience en psychologie sportive, on s'est rendu compte que chez les athlètes masculins, en situation de compétition relativement à celle de non compétition, il y a une augmentation du nombre de comportements complexes émis, mais qu'il y a une augmentation du nombre de comportements complexes émis, mais qu'il y a une baisse de la qualité de ceux-ci.

5. Des élèves du cours de psychologie expérimentale veulent étudier les sentiments de culpabilité des individus selon le type de délit qu'ils ont commis.

6. Un journaliste fait l'examen du pourcentage des intentions de vote des différents partis politiques québécois selon la langue parlée à la maison, le groupe d'âge et le degré de scolarité des électeurs.

## Exercice 3: Type de variables

Voici une série de question issue d'un questionnaire:

1. Quel est ton sexe? Homme, Femme : **nominal**
2. Quel est ton âge? ___________ (en années) **ratio**
3. Tu es en quelle année? 1e année, 2e année, junior, senior, autres **ordianale**
4. Vis-tu sur le campus ou fais-tu la navette hors campus? Sur le campus, hors campus **nominale**
5. Quelle est ton ethnie/race?  ___________________ **nominale**
6. Te considères-tu comme un fumeur? Oui, Non **nominae**
  a. Si oui, combien de cigarettes fumes-tu en moyenne par semaine? ____ **ratio**
  b. Si oui, depuis combien d'années fumes-tu? ___________ **ratio**
  c. Si oui, aimerais-tu cesser de fumer? Oui, Non **nominal**
7. As-tu déjà essayé de cesser de fumer? Oui, Non  **nominale**
  a. Si oui, combien de fois as-tu essayé? ______________ **ratio**

Pour chacune de ces question, dites le type de mesure de la variable ?
