---
title: "Seance 2: Les statistiques et les variables"
subtitle: "Discussion en classe"
author: "Visseho Adjiwanou, PhD."
institute: "Département de Sociologie - UQAM"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  beamer_presentation:
    colortheme: beaver
    fonttheme: structurebold
    theme: Ilmenau
  slidy_presentation: default
  ioslides_presentation: default
header-includes:
  - \usepackage{color}
---

## Résumé des informations

Termes                   Définition                            
------------------------ ----------------------------------------------------------------------
Variable                 Tout ce qui varie d'un cas à l'autre ou 
                         un ensemble logique d'attributs
Modalités / attribut     Une caractéristique d'une variable    
Variable dépendante      Une variable dépendante dans un problème 
                         est la donnée 
Variable indépendante    du problème qui varie sous l'influence de 
                         la variable indépendante 
Conceptualisation        Le processus de définition de ce que l'on 
                         entend par une variable
Opérationnalisation      Le processus de création d'une mesure réelle 
                         pour une variable

## Résumé des informations

Termes                   Définition                             
------------------------ -----------------------------------------------------------------------
Niveaux de mesure        Nominale, Ordinale, Intervalle, Ratio
Variable nominale        Une variable pour laquelle les attributs ne peuvent 
                         pas être classés du plus grand au plus petit
Variable ordinale        Une variable pour laquelle les attributs peuvent 
                         être classés de haut en bas, mais ne prennent pas 
                         la forme numérique
Variable intervalle      Une variable pour laquelle les attributs peuvent 
                         être classés de haut en bas parce qu'ils prennent 
                         une forme numérique.
Variable ratio           Une variable pour laquelle les attributs peuvent 
                         être classés de haut en bas parce qu'ils prennent 
                         une forme numérique.

## Résumé des informations

Termes                      Définition                             
--------------------------- -----------------------------------------------------------------------
Mutuellement exclusive      une condition qui existe lorsqu'un cas 
                            correspond à un et un seul attribut 
                            d'une variable
Collectivement exhaustive   Une condition qui existe lorsque 
                            les attributs d'une variable épuisent 
                            toutes les valeurs possibles que les 
                            cas peuvent avoir
Validité                    Le degré auquel une mesure reflète 
                            l'idée qu'elle était censée mesurer
Fiabilité                   La mesure dans laquelle une mesure donne 
                            des résultats cohérents entre les échantillons.

## Étude de cas 1: La question linguistique au Québec


