---
title: "labo9_blue"
author: Generated by BlueSky Statistics, LLC
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M:%S')`" 
output:
  html_document: default
R Version: 4.1.0
BlueSkyStatistics Version: 10.0b2
---


```{r setup-libraries, echo= FALSE, eval= TRUE, include = FALSE}
library(dplyr)
library(rmarkdown) 
library(kableExtra)
library(BlueSky)
library(gdata)
library(stringr)
library(openxlsx)
library(haven)
library(readr)
library(readxl)
library(data.table)
library(foreign)



# The folowing is needed if R Studio needs to Knit to PDF
#library(tinytex)
```

```{r setup-knitr-options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)

# Will keep the one single global graphics device open for all the code chunks 
#knitr::opts_knit$set(global.device = TRUE)

# Will output all the graphics - otherwise only the last graphics will be shown
knitr::opts_knit$set(fig.keep = 'all')

# To see the fully rendered output not the markup
knitr::opts_chunk$set(results='asis')

# Comment the above and un-comment the below to see the non rendered markup output
#knitr::opts_chunk$set(results="markup")
```

```{r BSky-config, eval= TRUE, include = FALSE}
        
#To flush internally all previously run BSkyFormat() output 
BSkyGetHoldFormatObjList()

# Sets up the default HTML output styling parameters 
BSkySetHtmlStylingSetting()

# Output Data cell - decimal points/engineering notation settings
#BSkySetDecimalDigitSetting(2)
#BSkySetEngNotationSetting(TRUE)
#BSkySetRound(TRUE)
#BSkySetPvalueDisplaySetting(FALSE)

# End of config set up 
```
# Open Dataset: Emploi_femme

```{r}
BSkyloadDataset('/Users/visseho/Library/CloudStorage/OneDrive-UQAM/Cours/SOC2206/S/Seance8_Association_intensite/Labo8/Emploi_femme.csv', 'CSV', worksheetName=NULL, replace_ds=TRUE, load.missing=FALSE, csvHeader=TRUE, character.to.factor=TRUE, isBasketData=FALSE, trimSPSStrailing=FALSE, sepChar=',', deciChar='.', datasetName='Emploi_femme')
BSkyLoadRefresh("Emploi_femme")
```
# Crosstab

```{r}
#Create the crosstab
BSky_Multiway_Cross_Tab = BSkyCrossTable(
    x=c('emploi'), y=c('sexe'), 
    datasetname='Emploi_femme', 
    chisq=TRUE, mcnemar=FALSE, fisher=FALSE,
    prop.r=FALSE, prop.c=TRUE,
    resid=FALSE, sresid=FALSE, asresid=FALSE,
    expected=FALSE)
#Display the crosstab in the output grid
BSkyFormat(BSky_Multiway_Cross_Tab)
```
# Remove NAs

```{r}

require(data.table)
#Removes missing values
#Emploi_femme_nm<-data.table:::na.omit.data.table(Emploi_femme[c('emploi','age','sexe','X___1')])
Emploi_femme_nm<-na.omit(Emploi_femme[c('emploi','age','sexe','X___1')])
#Refreshes the dataset in the data grid
BSkyLoadRefresh("Emploi_femme_nm")
 
```
# Recode Variables

```{r}

require(car)
#Perform the recode
BSkyRecode(colNames=c('emploi'), newColNames=c('emploi1'), OldNewVals='- = NA', NewCol=TRUE, dontMakeFactor =FALSE,dataSetNameOrIndex='Emploi_femme_nm')
#Refresh the dataset in the data grid
BSkyLoadRefresh("Emploi_femme_nm")

```
# Recode Variables

```{r}

require(car)
#Perform the recode
BSkyRecode(colNames=c('emploi'), newColNames=c('Emploi_rec'), OldNewVals='"-" = NA', NewCol=TRUE, dontMakeFactor =FALSE,dataSetNameOrIndex='Emploi_femme_nm')
#Refresh the dataset in the data grid
BSkyLoadRefresh("Emploi_femme_nm")

```
# Crosstab

```{r}
#Create the crosstab
BSky_Multiway_Cross_Tab = BSkyCrossTable(
    x=c('emploi'), y=c('sexe'), 
    datasetname='Emploi_femme_nm', 
    chisq=TRUE, mcnemar=FALSE, fisher=FALSE,
    prop.r=FALSE, prop.c=TRUE,
    resid=FALSE, sresid=FALSE, asresid=FALSE,
    expected=FALSE)
#Display the crosstab in the output grid
BSkyFormat(BSky_Multiway_Cross_Tab)
```
# Crosstab

```{r}
#Create the crosstab
BSky_Multiway_Cross_Tab = BSkyCrossTable(
    x=c('Emploi_rec'), y=c('sexe'), 
    datasetname='Emploi_femme_nm', 
    chisq=TRUE, mcnemar=FALSE, fisher=FALSE,
    prop.r=FALSE, prop.c=TRUE,
    resid=FALSE, sresid=FALSE, asresid=FALSE,
    expected=FALSE)
#Display the crosstab in the output grid
BSkyFormat(BSky_Multiway_Cross_Tab)
```
# Crosstab

```{r}
#Create the crosstab
BSky_Multiway_Cross_Tab = BSkyCrossTable(
    x=c('Emploi_rec'), y=c('sexe'), 
    datasetname='Emploi_femme_nm', 
    chisq=FALSE, mcnemar=FALSE, fisher=FALSE,
    prop.r=FALSE, prop.c=FALSE,
    resid=FALSE, sresid=FALSE, asresid=FALSE,
    expected=FALSE)
#Display the crosstab in the output grid
BSkyFormat(BSky_Multiway_Cross_Tab)
```
# Crosstab

```{r}
#Create the crosstab
BSky_Multiway_Cross_Tab = BSkyCrossTable(
    x=c('Emploi_rec'), y=c('sexe'), 
    datasetname='Emploi_femme_nm', 
    chisq=FALSE, mcnemar=FALSE, fisher=FALSE,
    prop.r=FALSE, prop.c=FALSE,
    resid=FALSE, sresid=FALSE, asresid=FALSE,
    expected=TRUE)
#Display the crosstab in the output grid
BSkyFormat(BSky_Multiway_Cross_Tab)
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme$sexe, Emploi_femme$Emploi_rec, chisq)
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme$sexe, Emploi_femme$Emploi_rec, chisq)
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme$sexe, Emploi_femme$Emploi_rec, chisq)
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme$sexe, Emploi_femme$Emploi_rec, chisq)
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme$sexe, Emploi_femme$Emploi_rec, chisq = TRUE)
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme_nm$sexe, Emploi_femme_nm$Emploi_rec, chisq = TRUE)
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme_nm$Emploi_rec, Emploi_femme_nm$sexe, chisq = TRUE)
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme_nm$Emploi_rec, Emploi_femme_nm$sexe, "c", chisq = TRUE)
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme_nm$Emploi_rec, Emploi_femme_nm$sexe, "c", chisq = TRUE)
rel <- table(Emploi_femme_nm$Emploi_rec, Emploi_femme_nm$sexe)
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme_nm$Emploi_rec, Emploi_femme_nm$sexe, "c", chisq = TRUE)
rel <- table(Emploi_femme_nm$Emploi_rec, Emploi_femme_nm$sexe)
rel
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme_nm$Emploi_rec, Emploi_femme_nm$sexe, "c", chisq = TRUE)
rel <- table(Emploi_femme_nm$Emploi_rec, Emploi_femme_nm$sexe)
rel
lamda(rel)
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme_nm$Emploi_rec, Emploi_femme_nm$sexe, "c", chisq = TRUE)
rel <- table(Emploi_femme_nm$Emploi_rec, Emploi_femme_nm$sexe)
rel
lambda(rel)
```
# R Console Script

```{r}
library(summarytools)
ctable(Emploi_femme_nm$Emploi_rec, Emploi_femme_nm$sexe, "c", chisq = TRUE)
rel <- table(Emploi_femme_nm$Emploi_rec, Emploi_femme_nm$sexe)
rel
lambda(rel)
```
