---
title: "Solution_Labo9"
author: Generated by BlueSky Statistics, LLC
date: "`r format(Sys.time(), '%d %B, %Y, %H:%M:%S')`" 
output:
  html_document: default
R Version: 4.1.0
BlueSkyStatistics Version: 10.0b2
---


```{r setup-libraries, echo= FALSE, eval= TRUE, include = FALSE}

#install.packages("remotes")
#remotes::install_github("BlueSkyStatistics/BlueSky")

#install.packages("vctrs", repos = "https://packagemanager.rstudio.com/cran/latest")
#install.packages("vctrs")
#install.packages("tibble")

library(tidyverse)
library(rmarkdown) 
library(kableExtra)
library(BlueSky)
library(gdata)
library(stringr)
library(openxlsx)
library(haven)
library(readr)
library(readxl)
library(data.table)
library(foreign)



# The folowing is needed if R Studio needs to Knit to PDF
#library(tinytex)
```

```{r setup-knitr-options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)

# Will keep the one single global graphics device open for all the code chunks 
#knitr::opts_knit$set(global.device = TRUE)

# Will output all the graphics - otherwise only the last graphics will be shown
knitr::opts_knit$set(fig.keep = 'all')

# To see the fully rendered output not the markup
knitr::opts_chunk$set(results='asis')

# Comment the above and un-comment the below to see the non rendered markup output
#knitr::opts_chunk$set(results="markup")
```

```{r BSky-config, eval= TRUE, include = FALSE}
        
#To flush internally all previously run BSkyFormat() output 
BSkyGetHoldFormatObjList()

# Sets up the default HTML output styling parameters 
BSkySetHtmlStylingSetting()

# Output Data cell - decimal points/engineering notation settings
#BSkySetDecimalDigitSetting(2)
#BSkySetEngNotationSetting(TRUE)
#BSkySetRound(TRUE)
#BSkySetPvalueDisplaySetting(FALSE)

# End of config set up 
```

1. Création de la variable quintile_revenu
# Custom R Code

```{r}

BSky_Dataset_Overview = data.frame(Dataset = c("cis_short_5percent_2015"),Variables = length(names(cis_short_5percent_2015)),Observations = nrow(cis_short_5percent_2015))
BSky_Numerical_Statistics_Analysis = BSkySummaryStats(datasetColumnObjects = list(CFATINC = cis_short_5percent_2015$CFATINC), groupByColumnObjects = list(), stats = c(min=FALSE, max=FALSE, mean=FALSE, median=FALSE, sum=FALSE, sd=FALSE, stderror=FALSE, iqr=FALSE, quantiles=TRUE), quantilesProbs = c(0, 0.20, 0.40, 0.60, 0.80, 1), additionalStats = c(), datasetName="cis_short_5percent_2015" )
BSkyFormat(BSky_Dataset_Overview, singleTableOutputHeader=c("Dataset Overview"))
BSkyFormat(BSky_Numerical_Statistics_Analysis, singleTableOutputHeader=c("Numerical Statistical Analysis by Variable"))
#remove(BSky_Dataset_Overview)
#remove(BSky_Numerical_Statistics_Analysis )

```
# Custom R Code

```{r}

require(car)
#Perform the recode
BSkyRecode(colNames=c('CFATINC'), newColNames=c('quintile_revenu'), OldNewVals='lo:36095 = "Tres riche"; 36095:58240 = "Riche"; 58240:83437 = "Moyen"; 83437:116959 = "Riche"; 116939:hi = "Tres riche"', NewCol=TRUE, dontMakeFactor =FALSE,dataSetNameOrIndex='cis_short_5percent_2015')
#Refresh the dataset in the data grid
BSkyLoadRefresh("cis_short_5percent_2015")

```
# Rank Variable(s)

```{r}

require(dplyr)
cis_short_5percent_2015 <- cis_short_5percent_2015 %>%
	mutate(q_CFATINC=ntile(CFATINC,5))
BSkyLoadRefresh("cis_short_5percent_2015")

```
# Custom R Code

```{r}

#Converts one or more variables to factor variables
BSky.Temp.Obj <- BSkyMakeMultiColumnFactor(c('quintile_revenu'), 'cis_short_5percent_2015')
#Refreshes the dataset in the data grid
BSkyLoadRefresh("cis_short_5percent_2015")

```
# Bar Chart

```{r}

## [Bar Chart With Counts]
require(ggplot2);
require(ggthemes);
require(stringr);
ggplot(data=cis_short_5percent_2015, aes(x=quintile_revenu)) +
	geom_bar(position="stack",alpha=1) +
	labs(x="quintile_revenu",y='Count',title= "Bar chart for X axis: quintile_revenu Y='Count' ") +
	xlab("quintile_revenu") +
	ylab("Count") + 
	theme_grey() + 
	theme(text=element_text(family="sans",
	face="plain",
	color="#000000",size=12,
	hjust=0.5,vjust=0.5))
```
# Frequency Table

```{r}

#Run the the frequency command            
BSkyFreqResults <- BSkyFrequency( vars = c('quintile_revenu') , data = cis_short_5percent_2015)
#Display the results
BSkyFormat(BSkyFreqResults)
#Remove the temporary object
if (exists('BSkyFreqResults')) rm (BSkyFreqResults)

```
# Frequency Table

```{r}

#Run the the frequency command            
BSkyFreqResults <- BSkyFrequency( vars = c('q_CFATINC') , data = cis_short_5percent_2015)
#Display the results
BSkyFormat(BSkyFreqResults)
#Remove the temporary object
if (exists('BSkyFreqResults')) rm (BSkyFreqResults)

```
# Convert To Factor(s)

```{r}

#Converts one or more variables to factor variables
BSky.Temp.Obj <- BSkyMakeMultiColumnFactor(c('quintile_revenu'), 'cis_short_5percent_2015')
#Refreshes the dataset in the data grid
BSkyLoadRefresh("cis_short_5percent_2015")

```
